const english = {
  trueApp: {
    tabScreen: {
      home: "Home",
      profile: "Profile",
      upload: "Upload",
      options: "Options",
      cart: "Shopping cart",
    },
    home: {
      results: "Results.",
      undo: "Undo",
      filteroder: "Filter/Order",
      filterorder_btn: "Filter and Ordering Options",
      homeCards: {
        notificacion: {
          title: "Image was correctly downloaded",
          body: ["You can find ", ".jpg in the folder Pictures/Downloads"],
        },
        details: "Details",
        handleAddCart: "Added to the Cart!",
        handleRemoveCart: "Removed from the Cart.",
        free: "Free",
        btnAddCart: "Add to Cart",
        btnRemoveCart: "Remove from cart",
        download: "Download",
        delete: "Delete",
      },
    },
    profile: {
      hi: "Hello!",
      login: "Log In",
      logout: "Log Out",
      follow: "Follow",
      unfollow: "Unfollow",
      followers: "Followers",
      following: "Following",
      publications: "Publications",
    },
    publication: {
      btn: "Upload Photo",
      title_placeholder: "Title...",
      descrip_placehodler: "Description...",
      take_photo: "Take Photo (Camera)",
      upload_file: "Upload Photo (File)",
      pay: ["Pay", "Free"],
      price: "Price...",
      price_error: "It only works whit positive numbers",
      tags: "Tags, Example:'yellow,forest,wild,dirt/autumn/beautiful/dog'",
      ubication: "Ubication...",
      reto: "Don't participate",
    },
    oherOptions: {
      home: "Home",
      upload: "Upload Photo",
      profile: "Profile",
      cart: "Shopping cart",
      language: "English",
      lightmode: "Mode Night/Day",
    },
    filterlang: {
      min: "Min. Price",
      max: "Max. Price",
      search: "Search...",
      reset: "Reset Filter",
      tipo: ["All", "Pay", "Free"],
      reto: "All chalenges",
      expired: "Expired",
    },
    cartlang: {
      empty: "The cart is empty",
      alert: {
        title: "Empty Cart",
        text: "You are about to delete all the content of your shopping cart, Are you sure you want to proceed?",
        btnOK: "Delete all",
        btnNo: "Kepp all",
      },
      buy: "Buy",
    },
    details: {
      alertTitle: "Delete Photo",
      alertDescritpion: "You are about to delete a photo for ever, are you sure you want to proced?",
      alertOk: "Yes, Delete photo",
      alertNotOk: "No!, Keep Photo",
    },
  },
};

export default english;
